namespace MdkLegal.Kernel;

/// <summary>
///     Represents a client's request to do work.
/// </summary>
public record Command
{
    /// <param name="id">
    ///     An identifier for the <see cref="Command" /> itself.
    ///     Could be used to check the request's progress if generated by the client.
    /// </param>
    public Command(Guid? id = null)
    {
        Id = id ?? Guid.NewGuid();
    }

    public Guid Id { get; }
}
