namespace MdkLegal.HelpDesk.Support.Services;

/// <summary>
///     Represents a client's request to do work.
/// </summary>
/// <param name="Id">
///     An identifier for the <see cref="Command" /> itself.
///     Could be used to check the request's progress if generated by the client.
/// </param>
public record Command(Guid Id);
